---
version: 0.5.0
slug: open3e
name: Open3e
description: Connect to E3 Controls through CAN
url: https://github.com/flecke-m/tree/master/open3e-ha-addon
arch:
  - amd64
  - armhf
  - aarch64
hassio_api: true
host_network: true
init: false
map:
  - addons:rw
  - all_addon_configs:rw
options:
  log_level: info
  log_to_file: false
  log_max_files: 7
schema:
  log_level: list(debug|verbose|http|info|warn|error)?
  log_to_file: bool?
  log_max_files: int(1,)?
services:
  - mqtt:need
startup: services
udev: true
usb: true
