---
version: 0.5.0
slug: open3e
name: Open3e
description: Connect to E3 Controls through CAN
url: https://github.com/flecke-m/tree/master/open3e-ha-addon
arch:
  - amd64
  - armhf
  - aarch64
hassio_api: true
host_network: true
init: false
map:
  - addon_config:rw
options: {
  "args": {}
}
privileged:
  - NET_ADMIN
schema:
  "args": {
      "can": "str?",
      "ca": "str?",
      "key": "str?",
      "cert": "str?",
      "user": "str?",
      "password": "str?",
      "base_topic": "str?"
  }
services:
  - mqtt:need
startup: services
udev: true
usb: true
