---
version: 0.5.0
slug: open3e
name: Open3e
description: Connect to E3 Controls through CAN
url: https://github.com/flecke-m/tree/master/open3e-ha-addon
arch:
  - amd64
  - armhf
  - aarch64
hassio_api: true
host_network: true
init: false
map:
  - addon_config:rw
options: {
  "main": {
    "can": "can0",
    "Listen-Topic": "open3e/cmnd"
  },
  "mqtt": {
    "Server:Topicname": "127.0.0.1:1883:open3e",
    "MQTT-User:Password": "testmqtt:test",
    "MQTT-Format-String": "{device}_{ecuAddr:03X}_{didNumber}_{didName}",
    "MQTT_ClientID": "open3e"
  }
}
privileged:
  - NET_ADMIN
schema: {
  "main": {
      "can": "str",
      "Listen-Topic": "str"
  },
  "mqtt": {
      "Server:Topicname": "str",
      "MQTT-User:Password": "str",
      "MQTT-Format-String": "str",
      "MQTT_ClientID": "str"
  }
}
services:
  - mqtt:need
startup: services